import './styles/icons.css';
import './styles/tailwind.css';
export {default as Button}from './components/inputs/Button';
export {default as TextInput} from './components/inputs/TextInput';
export {default as Select} from './components/inputs/Select/index';
export {default as Card} from './components/visuals/Card';
export {default as Popup}from './components/visuals/Popup';
export {default as Header} from './components/visuals/Header';
export {default as Tabs} from './components/controllers/Tabs';
export {default as Slider} from './components/inputs/Silder';